nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/': ~
